/*
 * SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Compatibility header: maps legacy cuVS names to muVS equivalents.
 * Include this header in code that was written for cuVS and is now being
 * compiled against the muVS (MUSA-backend) package.
 *
 * Generated by tools/musa/rename_cuvs_to_muvs.py
 */

#pragma once

#include <muvs/core/c_api.h>

#define cuvsError_t muvsError_t
#define cuvsResources_t muvsResources_t
#define cuvsStream_t muvsStream_t
#define cuvsLogLevel_t muvsLogLevel_t
#define cuvsResourcesCreate muvsResourcesCreate
#define cuvsResourcesDestroy muvsResourcesDestroy
#define cuvsStreamSet muvsStreamSet
#define cuvsStreamGet muvsStreamGet
#define cuvsStreamSync muvsStreamSync
#define cuvsDeviceIdGet muvsDeviceIdGet
#define cuvsRMMAlloc muvsRMMAlloc
#define cuvsRMMFree muvsRMMFree
#define cuvsGetLastErrorText muvsGetLastErrorText
#define cuvsSetLastErrorText muvsSetLastErrorText
#define cuvsGetLogLevel muvsGetLogLevel
#define cuvsSetLogLevel muvsSetLogLevel
#define cuvsVersionGet muvsVersionGet
#define cuvsMatrixCopy muvsMatrixCopy
#define cuvsMatrixSliceRows muvsMatrixSliceRows
#define CUVS_ERROR MUVS_ERROR
#define CUVS_SUCCESS MUVS_SUCCESS
#define cuvsRMMPoolMemoryResourceEnable muvsRMMPoolMemoryResourceEnable
#define cuvsRMMMemoryResourceReset muvsRMMMemoryResourceReset
#define cuvsRMMHostAlloc muvsRMMHostAlloc
#define cuvsRMMHostFree muvsRMMHostFree
